////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;

namespace NosByte.Packets.ClientPackets
{
    [PacketHeader("fhis_cts")]
    public class FhistCtsPacket : PacketDefinition
    {
        #region Properties        

        #endregion
    }
}