////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;

namespace NosByte.Packets.ClientPackets
{
    [PacketHeader("pdtse")]
    public class PdtsePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Type { get; set; }

        [PacketIndex(1)]
        public short VNum { get; set; }

        [PacketIndex(2)]
        public byte? Unknown { get; set; }

        [PacketIndex(3)]
        public short? EquipmentSlot { get; set; }

        [PacketIndex(4)]
        public byte Option { get; set; }





        #endregion
    }
}