////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;

namespace NosByte.Packets.ClientPackets
{
    [PacketHeader("pleave")]
    public class PLeavePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}