////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;

namespace NosByte.Packets.ClientPackets
{
    [PacketHeader("preq")]
    public class PreqPacket : PacketDefinition
    {
        #region Properties
        
        [PacketIndex(0)]
        public short? Parameter { get; set; }
        
        #endregion
    }
}