////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.Lock
{
    [PacketHeader("$SetLockCode", "$Code", PassNonParseablePacket = true, Authority =  AuthorityType.User)]
    public class SetLockCodePacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string Code { get; set; }

        #region Properties

        public static string ReturnHelp() => "$SetLockCode <Code>";

        #endregion
    }
}