////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Act4Stat", PassNonParseablePacket = true, Authority = AuthorityType.GD)]
    public class Act4StatPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public FactionType Faction { get; set; }

        [PacketIndex(1)]
        public int Value { get; set; }

        public static string ReturnHelp() => "$Act4Stat <Faction> <Value>";

        #endregion
    }
}