////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$AddGold", PassNonParseablePacket = true, Authority =  AuthorityType.GM )]
    public class AddGoldPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public long Amount { get; set; }

        public static string ReturnHelp() => "$AddGold <Value> (Current Gold + Added Gold = MAX. 2.000.000.000)";

        #endregion
    }
}