////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$AddSkill", PassNonParseablePacket = true, Authority =  AuthorityType.TM )]
    public class AddSkillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short SkillVNum { get; set; }

        public static string ReturnHelp() => "$AddSkill <VNum>";

        #endregion
    }
}