////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$ArenaWinner", PassNonParseablePacket = true, Authority =  AuthorityType.GM )]
    public class ArenaWinnerPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$ArenaWinner";
    }
}