////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Lvl", PassNonParseablePacket = true, Authority =  AuthorityType.GD )]
    public class ChangeLevelPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Level { get; set; }

        public static string ReturnHelp() => "$Lvl <Value>";

        #endregion
    }
}