////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$ClassPack", PassNonParseablePacket = true, Authority =  AuthorityType.BA)]
    public class ClassPackPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short Class { get; set; }

        public static string ReturnHelp() => "$ClassPack <ClassType[1 = Swordsman, 2 = Archer, 3 = Mage]>";

        #endregion
    }
}