////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$ClearMap", PassNonParseablePacket = true, Authority =  AuthorityType.GD )]
    public class ClearMapPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ClearMap";

        #endregion
    }
}