////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$FamilyFaction", PassNonParseablePacket = true, Authority =  AuthorityType.SMOD )]
    public class FamilyFactionPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string FamilyName { get; set; }

        public static string ReturnHelp() => "$FamilyFaction <Name>";
    }
}