////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$HairColor", PassNonParseablePacket = true, Authority =  AuthorityType.TMOD )]
    public class HairColorPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public HairColorType HairColor { get; set; }

        public static string ReturnHelp() => "$HairColor <Value>";

        #endregion
    }
}