////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Invisible" , PassNonParseablePacket = true, Authority = AuthorityType.GS)]
    public class InvisiblePacket : PacketDefinition
    {
        public static string ReturnHelp() => "$Invisible";
    }
}