////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$ResetMap" , PassNonParseablePacket = true, Authority =  AuthorityType.GD )]
    public class MapResetPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ResetMap";

        #endregion
    }
}