////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$MapStat", PassNonParseablePacket = true, Authority =  AuthorityType.BA )]
    public class MapStatisticsPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short? MapId { get; set; }

        #endregion

        #region Methods

        public static string ReturnHelp() => "$MapStat <?MapId>";

        #endregion
    }
}