////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Miniland", PassNonParseablePacket = true, Authority =  AuthorityType.BA )]
    public class MinilandPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public string CharacterName { get; set; }

        public static string ReturnHelp()
        {
            return "$Miniland <?Nickname>";
        }

        #endregion
    }
}