////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$ReloadSI" , PassNonParseablePacket = true, Authority =  AuthorityType.TM )]
    public class ReloadSIPacket : PacketDefinition
    {
        #region Properties
        
        public static string ReturnHelp() => "$ReloadSI";

        #endregion
    }
}