////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Restart", PassNonParseablePacket = true, Authority =  AuthorityType.TM )]
    public class RestartPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Time { get; set; }

        public static string ReturnHelp() => "$Restart <?Delay>";
    }
}