////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$SPRefill", PassNonParseablePacket = true, Authority =  AuthorityType.GD )]
    public class SPRefillPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$SPRefill";
    }
}