////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$StartAct4", PassNonParseablePacket = true, Authority =  AuthorityType.Administrator)]
    public class StartAct4Packet : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$StartAct4";

        #endregion
    }
}