////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Stat", PassNonParseablePacket = true, Authority =  AuthorityType.GD )]
    public class StatCommandPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$Stat";
    }
}