////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Core.Serializing;
using OpenNos.Domain;

namespace NosByte.Packets.CommandPackets
{
    [PacketHeader("$Unsave", PassNonParseablePacket = true, Authority = AuthorityType.GM)]
    public class UnsavePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string AccountName { get; set; }


        public static string ReturnHelp() => "$Unsave <Accountname>";

        #endregion
    }
}